baseURL = 'https://badw.github.io/'
languageCode = 'en-gb'
title = 'website for Benjamin A. D. Williamson'
defaultContentLanguage = 'en'
enableGitInfo = true
timeout='5m'

[caches.images]
dir = ':cacheDir/images'
maxAge = "1440h" # 60days

googlefonts = ["PT Sans", "Droid Sans", "Fira Mono"]
#fontbody = 'Droid Sans'
fontbody = 'PT Sans'
fontcode = 'Fira Mono'
